app:
    image: chrismckinnel/devops-battlefield-local:latest
    ports:
        - "8001:8001"
    environment:
        - ENV=local
        - PORT=8001
    volumes:
        - "/containers/devops:/host"
        - "www:/var/www"
 
# postgres:
#     image: postgres:latest
#     environment:
#         - POSTGRES_PASSWORD=devops
#         - POSTGRES_USER=devops
#         - POSTGRES_DB=devops
#     command: postgres
#     ports:
#         - "5432:5432"